### ISSUE TITLE
It does not work out with url-loader.

### ISSUE THREAD

**Issue by brandonxiang** [tcoopman/image-webpack-loader#101]
It does not work out with url-loader in webpack2 of vue2 project.

```
          {
            loader: 'url-loader',
            options: {
              limit: 10000,
              name: utils.assetsPath('img/[name].[hash:7].[ext]')
            }
          },
          {
            loader: 'image-webpack-loader',
            options: {
              mozjpeg: {
                quality: 65
              },
              pngquant: {
                quality: "65-90",
                speed: 4
              },
              gifsicle: {
                optimizationLevel: 7,
                interlaced: false
              },
              optipng: {
                optimizationLevel: 7,
                interlaced: false
              }
            }
          }
```

Those pngs have never been parsed out.

Would you mind making a test for "url-loader"?

**Comment by guoerwei** [comment]
+1
```
ERROR in ./src/assets/icon/msgbox-close.png
    Module build failed: Error: spawn /project-dir/node_modules/pngquant-bin/vendor/pngquant ENOENT
        at exports._errnoException (util.js:1022:11)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
        at onErrorNT (internal/child_process.js:359:16)
        at _combinedTickCallback (internal/process/next_tick.js:74:11)
        at process._tickCallback (internal/process/next_tick.js:98:9)
     @ ./~/css-loader?minimize!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-2e77862f","scoped":false,"hasInlineConfig":true}!./~/less-loader/dist!./src/styles/common.less 6:8697-8739
```

**Comment by brandonxiang** [comment]
Finally, I figured it out. The image has been compressed and then converted into base64.

**Comment by zmj97** [comment]
> Finally, I figured it out. The image has been compressed and then converted into base64.

@brandonxiang   请问最后你是怎么解决的？
