### ISSUE TITLE
module build failed

### ISSUE THREAD

**Issue by YiXingYuFeng** [tcoopman/image-webpack-loader#104]
ERROR in ./img/test.jpg
    Module build failed: Error: spawn /Users/tianxiaoli/Desktop/node /webPack-Test/test-Image-webpack-loader/node_modules/mozjpeg/vendor/cjpeg ENOENT  

how to solve?  Thanks

**Comment by frontEnd-fucker** [comment]
i have the same issue

**Comment by iakovmarkov** [comment]
I've got the same issue, any idea on how to fix? It feels like some peer dependency is broken.

**Comment by fitzr** [comment]
Downgrading "p-pipe" from "1.2.0" to "1.1.0" fixed my issue.

**Comment by fitzr** [comment]
Downgrading  "file-loader" from "1.0.0" to "0.9.0" fixed my issue.

**Comment by iakovmarkov** [comment]
@fitzr doesn't work for me.

**Comment by Zephir77167** [comment]
Hi, could you provide a little more information please? Starting with your package.json so it would be easier to identify the problem. Thanks in advance!

**Comment by daphnesmit** [comment]
I have the same..
`
ERROR in ./src/packages/brenntag-assets/images/background.jpg
Module build failed: Error: spawn /tamtam/digib-imp-front-end/node_modules/mozjpeg/vendor/cjpeg ENOENT
    at _errnoException (util.js:1041:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

    "file-loader": "^0.11.2",
    "image-webpack-loader": "^3.4.2",

**Comment by Zephir77167** [comment]
It _looks_ like your issue is coming from `mozjpg`, which is a dependency of `image-webpack-loader`. Could you please post an issue on their repository?

**Comment by daphnesmit** [comment]
I have the same for pngquant. These devDependencies are also out of date. maybe has to do with that?

**Comment by Zephir77167** [comment]
Are you on MacOS? If so, have you run `brew install libpng`? (See Readme)

**Comment by daphnesmit** [comment]
its on docker.

**Comment by Zephir77167** [comment]
Could you please provide some OS information (also node version) and maybe the image that caused the crash so I could dig a little bit?

**Comment by Tzrong** [comment]
this is my pakage.json
`"css-loader": "^3.4.0",
    "file-loader": "^5.0.2",
    "html-webpack-plugin": "^3.2.0",
    "image-webpack-loader": "^6.0.0",`
Originally the project was started normally. After adding a picture, the error is as follows
![image](https://user-images.githubusercontent.com/24354441/71808610-31b87580-30a9-11ea-9c52-08922050cb2e.png)
my computer is Mac, and node version id 10.15.3

**Comment by NKovp** [comment]
Try `npm rebuild`. Fixed for me

**Comment by ssk-dev** [comment]
@NKovp you made my day

**Comment by gloveit** [comment]
I have the same issue. How to resolve it???

**Comment by swlilike** [comment]
it fixed for me
1， delete `node_modules`
2，`cnpm install`  ，be careful，it's cnpm。
3，build， OK~

**Comment by 18210075779** [comment]
You can try use cnpm to install image-webpack-loader.

**Comment by djego** [comment]
Also you can to try with: 
`npm rebuild mozjpeg`
`npm rebuild pngquant`
`npm rebuild gifsicle`

Work for me
