### ISSUE TITLE
No nasm found with 4.0.0

### ISSUE THREAD

**Issue by andrenarchy** [tcoopman/image-webpack-loader#137]
I'm getting the following error with version 4.0.0:

```
  ⚠ The `/home/travis/build/paperhive/paperhive-frontend/node_modules/image-webpack-loader/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --disable-dependency-tracking --with-jpeg8  --prefix="/home/travis/build/paperhive/paperhive-frontend/node_modules/image-webpack-loader/node_modules/mozjpeg/vendor" --bindir="/home/travis/build/paperhive/paperhive-frontend/node_modules/image-webpack-loader/node_modules/mozjpeg/vendor" --libdir="/home/travis/build/paperhive/paperhive-frontend/node_modules/image-webpack-loader/node_modules/mozjpeg/vendor" && make -j2 && make install -j2
Command failed: ./configure --disable-shared --disable-dependency-tracking --with-jpeg8  --prefix="/home/travis/build/paperhive/paperhive-frontend/node_modules/image-webpack-loader/node_modules/mozjpeg/vendor" --bindir="/home/travis/build/paperhive/paperhive-frontend/node_modules/image-webpack-loader/node_modules/mozjpeg/vendor" --libdir="/home/travis/build/paperhive/paperhive-frontend/node_modules/image-webpack-loader/node_modules/mozjpeg/vendor"
configure: error: no nasm (Netwide Assembler) found
    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:160:13)
    at Pipe._handle.close [as _onclose] (net.js:559:12)
```

**Comment by hsz** [comment]
Same here:

```
> mozjpeg@5.0.0 postinstall /opt/bitnami/apps/jenkins/jenkins_home/jobs/Project/workspace/node_modules/mozjpeg
> node lib/install.js

  ⚠ The `/opt/bitnami/apps/jenkins/jenkins_home/jobs/Project/workspace/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --disable-dependency-tracking --with-jpeg8  --prefix="/opt/bitnami/apps/jenkins/jenkins_home/jobs/Project/workspace/node_modules/mozjpeg/vendor" --bindir="/opt/bitnami/apps/jenkins/jenkins_home/jobs/Project/workspace/node_modules/mozjpeg/vendor" --libdir="/opt/bitnami/apps/jenkins/jenkins_home/jobs/Project/workspace/node_modules/mozjpeg/vendor" && make -j2 && make install -j2
Command failed: ./configure --disable-shared --disable-dependency-tracking --with-jpeg8  --prefix="/opt/bitnami/apps/jenkins/jenkins_home/jobs/Project/workspace/node_modules/mozjpeg/vendor" --bindir="/opt/bitnami/apps/jenkins/jenkins_home/jobs/Project/workspace/node_modules/mozjpeg/vendor" --libdir="/opt/bitnami/apps/jenkins/jenkins_home/jobs/Project/workspace/node_modules/mozjpeg/vendor"
./configure: line 13124: PKG_PROG_PKG_CONFIG: command not found
./configure: line 13303: syntax error near unexpected token `libpng,'
./configure: line 13303: `PKG_CHECK_MODULES(libpng, libpng, HAVE_LIBPNG=1,'

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

https://github.com/imagemin/mozjpeg-bin/issues/35

**Comment by anikethsaha** [comment]
It needs to be resolved from `mozjpeg-bin` side. After they fix it, this loader will update the dependency
