### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by DanielMSchmidt** [tcoopman/image-webpack-loader#153]
Hey there, 
Thank you for this awesome project 👍 

I would like to use it in a webpack 4 environment (at least we would like to upgrade soon), so I thought I'll file a ticket.
I tried to extend the tests to include webpack 4 and I got this error:

```
+ webpack-cli@2.0.14
added 321 packages in 13.282s
Hash: 9a55d99f75ef727ec3a6
Version: webpack 4.5.0
Child
    Hash: 9a55d99f75ef727ec3a6
    Time: 3488ms
    Built at: 2018-4-10 10:25:24
     1 asset
    Entrypoint main = app.9a55d99f75ef727ec3a6.js
       [0] ./test/test.bmp 221 bytes {0} [built] [failed] [1 error]
       [1] ./test/test.svg 221 bytes {0} [built] [failed] [1 error]
       [2] ./test/test.png 221 bytes {0} [built] [failed] [1 error]
       [3] ./test/test.jpg 221 bytes {0} [built] [failed] [1 error]
       [4] ./test/test.gif 221 bytes {0} [built] [failed] [1 error]
       [5] ./test/app.js 115 bytes {0} [built]

    WARNING in configuration
    The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
    You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

    ERROR in ./test/test.svg
    Module build failed: TypeError: Cannot read property 'fileLoader' of undefined
        at Object.module.exports (/Users/danielschmidt/projects/image-webpack-loader/node_modules/file-loader/index.js:13:28)
     @ ./test/app.js 4:0-21

    ERROR in ./test/test.bmp
    Module build failed: TypeError: Cannot read property 'fileLoader' of undefined
        at Object.module.exports (/Users/danielschmidt/projects/image-webpack-loader/node_modules/file-loader/index.js:13:28)
     @ ./test/app.js 5:0-21

    ERROR in ./test/test.gif
    Module build failed: TypeError: Cannot read property 'fileLoader' of undefined
        at Object.module.exports (/Users/danielschmidt/projects/image-webpack-loader/node_modules/file-loader/index.js:13:28)
     @ ./test/app.js 1:0-21

    ERROR in ./test/test.png
    Module build failed: TypeError: Cannot read property 'fileLoader' of undefined
        at Object.module.exports (/Users/danielschmidt/projects/image-webpack-loader/node_modules/file-loader/index.js:13:28)
     @ ./test/app.js 3:0-21

    ERROR in ./test/test.jpg
    Module build failed: TypeError: Cannot read property 'fileLoader' of undefined
        at Object.module.exports (/Users/danielschmidt/projects/image-webpack-loader/node_modules/file-loader/index.js:13:28)
     @ ./test/app.js 2:0-21
```

AFAIK webpack 4 introduced some breaking changes, I guess here they are 🙈

**Comment by DanielMSchmidt** [comment]
No I haven't thank you 👍 I will try to verify this and close the ticket if it works 👍

**Comment by aimamisa** [comment]
This npm install --save-dev file-loader@1.1.11 perfectly works for me

**Comment by fengcaian** [comment]
nice

**Comment by DanielMSchmidt** [comment]
Sorry, forgot to close
