### ISSUE TITLE
webpack build errors after upgrading from 4.3.0 to 4.3.1

### ISSUE THREAD

**Issue by doberkofler** [tcoopman/image-webpack-loader#158]
After upgrading image-webpack-loader from 4.3.0 to 4.3.1 i get a ton of errors as follows:

```
ERROR in ./src/modules/dashboard/jquery.dashboard.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
ReferenceError: Unknown plugin "transform-class-properties" specified in "base" at 2, attempted to resolve relative to "D:\\MyDev\\ljs_app\\trunk\\periscope\\bu
ild\\src\\modules\\dashboard"
    at D:\MyDev\ljs_app\trunk\periscope\build\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\babel-loader\lib\index.js:173:20)
```

As there are absolutely no other changes in the configuration, the problem seems to be related to the upgrade of `image-webpack-loader` and any help would be appreciated.

webpack: 4.12.0
node: 10.4.0
os: Windows

**Comment by tcoopman** [comment]
[This](https://github.com/tcoopman/image-webpack-loader/commit/2bcd82f5b7c036cca02415d5bc6b09de06faa094) is the only change in from 4.3.0 to 4.3.1, so seems strange that it would be the cause of this.

**Comment by doberkofler** [comment]
@tcoopman I understand! I only opened the SR because I was able to exactly pin down the errors to this one upgrade. With the upgrade i get the error and if I undo the update it works again.
@jmenache You gave my SR a thumbs up and might have some more information on your problem?

**Comment by Jmenache** [comment]
@doberkofler I don't have more information unfortunately.
When tried to upgrade, I got the error same error as you, when I downgraded my version, the error disappeared.

webpack: 4.12.0
webpack-cli: 3.0.3,
node: 8.11.2
npm: 6.1.0
os: Windows

@tcoopman I confirm the upgrade caused the error in our build.

**Comment by tcoopman** [comment]
@goto-bus-stop can you take a look at why this could be failing?

**Comment by doberkofler** [comment]
@tcoopman I'm currently also having a very strange npm problem https://npm.community/t/npm-err-cannot-read-property-match-of-undefined. It does not seem to relate to this issue but maybe...?

**Comment by goto-bus-stop** [comment]
Bizarre…the only possibly related thing I can think of is that 4.3.0 installed a ton of dependencies including Babel plugins. If you used one of those plugins in your babelrc but haven't listed them in your own package.json, the upgrade would cause these errors. If that's it, the fix is to manually install those plugins. If not, it would be great if you could share a babelrc and package.json so I can try reproduce it

**Comment by goto-bus-stop** [comment]
That does appear to be a package-lock.json issue so it might well be related :thinking:

**Comment by doberkofler** [comment]
@goto-bus-stop You nailed it and I'm ashamed not to have checked before. `babel-plugin-transform-class-properties` was not in the dependencies and caused the problem. Thank you very much!
