### ISSUE TITLE
Cannot find module 'gifsicle'

### ISSUE THREAD

**Issue by MrLongSiYuan** [tcoopman/image-webpack-loader#233]
When I build,An error has occurred：

Error: Cannot find module 'gifsicle'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
my webpack.config.js:
               test:/\.(svg|png|gif|jpe?g)$/,
                use:[
                    {
                        loader:'file-loader',
                        options:{
                            name:'[name]_[hash:8].[ext]'
                        }
                    },
                     'image-webpack-loader', 
                ]

**Comment by jiangtong** [comment]
use cnpm

**Comment by mezhanglei** [comment]
i guess you used official source from yarn，you can use other source

**Comment by danman113** [comment]
+1 for this. Having the same issue on alpine linux

**Comment by quocthangit247** [comment]
+1 for this. I am using ubuntu 20.04 with ver 7.0.0. How can I resolve this problem ??? thanks

**Comment by milkins87** [comment]
+1 for this. Having the same issue on linux

**Comment by enrique-ramirez** [comment]
+1. This seems to be the underlying issue: https://github.com/imagemin/gifsicle-bin/issues/113 this prevents us from building on our host, and I haven't found a viable solution other than installing the dependencies on the server (which is not scalable, really). If anyone has an alternative, it'd be great.

**Comment by Marszht** [comment]
i met the same qa
