### ISSUE TITLE
Strange error message when compressing gif files

### ISSUE THREAD

**Issue by doberkofler** [tcoopman/image-webpack-loader#34]
I've been using the `image-webpack-loader` for a while but (only!) when loading `gif` files with the this
```
{
	test: /\.(png|gif|jpe?g|svg)$/i,
	loaders: [
		'url-loader?limit=1&name=img/[name].[ext]',
		'image-webpack-loader?{progressive: true, optimizationLevel: 7, interlaced: false, pngquant: {quality: "65-90", speed: 4}}'
	]
}
```
loader configuration, I get the following error that does not really help me at all:
```
Module build failed: TypeError: Cannot read property 'charCodeAt' of undefined
    at isBinary (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\is-svg\index.js:8:38)
    at module.exports (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\is-svg\index.js:19:10)
    at buf (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\imagemin-svgo\index.js:8:7)
    at Imagemin.use (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\image-webpack-loader\node_modules\imagemin\index.js:63:51)
    at Object.module.exports (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\image-webpack-loader\index.js:33:6)
 @ ./libs/select2/select2.css 6:18424-18450
```

Any help would be appreciated.

**Comment by tcoopman** [comment]
Can you give me the file that fails?
It looks like an issue with https://github.com/sindresorhus/is-svg.

**Comment by doberkofler** [comment]
sure:
![select2-spinner](https://cloud.githubusercontent.com/assets/1009585/16522573/f803039a-3f9e-11e6-8d67-ac2ea1d23c74.gif)

**Comment by tcoopman** [comment]
I've updated to a new version imagemin. Can you check if you still have the issue with 2.0?

**Comment by doberkofler** [comment]
@tcoopman It does work now. Thank you!
