### ISSUE TITLE
Mozjpeg test fails and then compilation fails

### ISSUE THREAD

**Issue by albertogasparin** [tcoopman/image-webpack-loader#49]
Just updated to v3 and got:

```
mozjpeg@4.1.1 postinstall /node_modules/mozjpeg
> node lib/install.js

  ⚠ The `/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --prefix="/node_modules/mozjpeg/vendor" --bindir="/node_modules/mozjpeg/vendor" --libdir="/node_modules/mozjpeg/vendor" && make --jobs=8 && make install --jobs=8
Command failed: /bin/sh -c autoreconf -fiv
/bin/sh: autoreconf: command not found

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:475:12)
```

**Comment by tcoopman** [comment]
Are you working with an older version of Ubuntu? Can you try `sudo apt-get install autoconf autogen`

**Comment by albertogasparin** [comment]
I'm on OSX 10.10. It looks like it is a [imagemin/mozjpeg issue](https://github.com/imagemin/imagemin-mozjpeg/issues/11). 

Would you evaluate the possibility to stick with imagemin-mozjpeg@5.0.0 until a new version of mozjpeg comes out? That is the latest version correctly installing on OS X as versions 5.1.0 onwards use an incompatible version on mozjpeg 😞

**Comment by tcoopman** [comment]
@pavelloz do you know what the impact is of this?

**Comment by pavelloz** [comment]
I tried to reproduce this problem and i failed on both OSX 10.11 and 10.12, dont have access to 10.10

@albertogasparin 
Have you tried installing `automake`, `autoconf`, `libtool`? 

From what I've read in here https://github.com/imagemin/mozjpeg-bin/issues/16 it might be the case of simply missing dependencies necessary to compile the sources.

**Comment by albertogasparin** [comment]
Yes, by installing all of them I was able to compile mozjpeg on my machine. The point I was highlighting is that as those tools are not available by default (and the error message is not that helpful) this webpack plugin now looks broken on OS X.
So, I was questioning if the benefits of mozjpeg v4 over v3 are worth the additional pain for your OS X users.
For what I'm concerned, I can stick with image-webpack-loader v2 as it works fine across all our machines, but new users might go elsewhere because the installation fails or it has to be compiled on every npm install.

**Comment by scholtzm** [comment]
Running OSX 10.11 and I ran into same issue.
Not sure if updating to image-webpack-loader `v3.x` is a viable option for us right now since this can possibly lead to fairly cryptic build error.

@albertogasparin Did you eventually update?

**Comment by albertogasparin** [comment]
No, I had to lock the version to v3, as it's to much of a hassle for all developers in my team. I hope that mozjpeg will eventually release a new version soon. Otherwise will need to fork/find a replacement whenever this v3 will stop working 😞

**Comment by tcoopman** [comment]
Is it enough for you if we put a warning in the readme that users of OSX
10.10 should install an older version?

**Comment by iiison** [comment]
I'm running into the same problem on mac 10.12.1. Not sure how to fix this.

**Comment by mikedpad** [comment]
I was able to get it working.
`brew install libtool`

I'm running MacOS Sierra 10.12.2 and was running into many of the same problems listed in similar threads. The mozjpeg pre-build test failed but I was able to build from source afterwards. This was working fine on El Capitan for me oddly enough but the update to Sierra broke it.

Also, if it's any help, I preceded that command with...
`brew install nasm`
`brew unlink automake && brew link automake`

**Comment by wsfuller** [comment]
Still unable to get this to work with the above suggestions.

macOS: 10.12.5
Webpack: 2.4.1
image-webpack-loader: ^3.3.0

**ERROR**

```
ERROR in ./src/assets/images/background.jpg
Module build failed: Error: spawn /Users/me/development/ccpam/frontend/node_modules/mozjpeg/vendor/cjpeg ENOENT
    at exports._errnoException (util.js:1034:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
 @ ./~/css-loader!./~/resolve-url-loader!./~/postcss-loader!./~/sass-loader/lib/loader.js!./src/index.scss 6:33080-33121
 @ ./src/index.scss
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.jsx
```

Tried Solutions:
`brew install libtool`
`brew install autoconf`

```
Warning: libtool-2.4.6_1 already installed
Warning: automake-1.15 already installed
Warning: autoconf-2.69 already installed
```

**Loader Config**

```
{
        test: /\.(jpe?g|png|gif|svg)$/,
        use: [imageConfig,{
          loader: 'image-webpack-loader',
          query: {
            mozjpeg: {
              progressive: true,
            },
            gifsicle: {
              interlaced: false,
            },
            optipng: {
              optimizationLevel: 4,
            },
            pngquant: {
              quality: '75-90',
              speed: 3,
            },
          }
        }],
      }
```

The `imageConfig` is just configuring environments and how to use File Loader.

**Comment by jpvincent** [comment]
Hi there
The solution you provided were not enough in my case, I first had to correct the brew installation itself. For posterity, and because this is one of the first issues that arises when googling, here are the steps that worked for me. I started from the brew FAQ "upgrading MacOS", http://docs.brew.sh/Common-Issues.html#upgrading-macos
* update XCode, run it, it will proceed to a few more installation
* `brew update` (updates brew itself)
* `brew upgrade` (upgrades all the packages)
* `npm uninstall image-webpack-loader` and `npm install image-webpack-loader`

hope this helps :)

**Comment by debasishshanti** [comment]
@albertogasparin Do you have a Package lock file that was generated from another OS? I faced this issue when a package-lock.json file was created in Windows system and then we tried to deploy the code in Jenkins(Linux) environment. Deleting the package-lock.json file solved the issue for me.
Hope this helps

**Comment by esbeeb** [comment]
In Debian Buster, I had to install the package "dh-autoreconf", which provided the expected app  autoreconf

**Comment by garbinmarcelo** [comment]
I have the same problem on CentOS 7. Any solutions to this?

**Comment by yangdan8** [comment]
I have the same problem on Windows 11. Any solutions to this?
