### ISSUE TITLE
bypassOnDebug is required

### ISSUE THREAD

**Issue by jadekler** [tcoopman/image-webpack-loader#90]
We see errors when we don't provide it. This seems like a bad thing - should it be turned on by default?

```
    ERROR in ./~/pui-css-backgrounds/images/gray-cloud.png
    Module build failed: TypeError: Cannot read property 'bypassOnDebug' of null
        at Object.module.exports (/Users/pivotal/workspace/go/src/github.com/pivotal-cf/platform-metrics-data/dashboard_app/src/main/resources/assets/node_modules/image-webpack-loader/index.js:30:26)
     @ ./~/css-loader!./~/sass-loader/lib/loader.js!./~/pui-css-backgrounds/backgrounds.css 6:63-97

    ERROR in ./~/pui-css-backgrounds/images/aboutus-hero.jpg
    Module build failed: TypeError: Cannot read property 'bypassOnDebug' of null
        at Object.module.exports (/Users/pivotal/workspace/go/src/github.com/pivotal-cf/platform-metrics-data/dashboard_app/src/main/resources/assets/node_modules/image-webpack-loader/index.js:30:26)
     @ ./~/css-loader!./~/sass-loader/lib/loader.js!./~/pui-css-backgrounds/backgrounds.css 6:319-355
```

**Comment by jadekler** [comment]
Fixing it simply requires switching from:

```
{
        test: /\.(jpe?g|png|gif|svg)$/i,
        loader: 'file-loader!image-webpack-loader'
      }
```

to

```
{
        test: /\.(jpe?g|png|gif|svg)$/i,
        loader: 'file-loader!image-webpack-loader&bypassOnDebug'
      }
```

**Comment by Zephir77167** [comment]
Can be closed, the PR has been merged
