### ISSUE TITLE
Bug in imagemin 5.3.0

### ISSUE THREAD

**Issue by kaicataldo** [tcoopman/image-webpack-loader#99]
Looks like there's an issue with the latest release of imagemin - would it be possible to lock the version to v5.2.2 until this is resolved?

https://github.com/imagemin/imagemin/issues/243

**Comment by jadekler** [comment]
Just got this problem too.

```
ERROR in ./images/panasonic_logo.png
Module build failed: TypeError: pPipe(...) is not a function
    at Function.module.exports.buffer (/Users/jeandeklerk/dev/go/src/codecommit/cdot/v2x-ops/node_modules/imagemin/index.js:64:60)
    at Object.module.exports (/Users/jeandeklerk/dev/go/src/codecommit/cdot/v2x-ops/node_modules/image-webpack-loader/index.js:67:8)
 @ ./src/components/TitleBar.js 37:22-64
 @ ./src/components/App.js
 @ ./src/app.js
```

**Comment by tcoopman** [comment]
It looks like the bug is fixed, please confirm

**Comment by kaicataldo** [comment]
Yes, it looks like it's been fixed! Closing.
